---
 width_spec: 1200
 height_spec: 800
 maximum_practice: 1
 maximum_time: 10
 easy_time_limit: 7
 hard_time_limit: 21
 probability: [12, 50, 88]
 reward_lowerbound: 1.24
 reward_higherbound: 4.3
 font_size: 25
